-- Steven Szachara
-- ISTE 608 PE03
-- Fall 2024

DROP DATABASE IF EXISTS PE3;

CREATE DATABASE PE3;

USE PE3;

CREATE TABLE Automobile (
	VIN			SMALLINT(5) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
	MAKE		VARCHAR(15),
	MODEL		VARCHAR(15),
	YEAR		CHAR(15),
	COLOR		CHAR(15),
	STYLE		CHAR(15),
	MSRP		DOUBLE,
	PRIMARY KEY (VIN)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

